### ISSUE TITLE
[BUG]: Using --lang typescript-zod, the generated code ignores regex fields

### ISSUE THREAD

**Issue by robogeek** [glideapps/quicktype#2556]
## Context (Environment, Version, Language)

Input Format:  JSON Schema written in YAML
Output Language: typescript-zod

CLI, npm, or app.quicktype.io:  "npx quicktype" using Node.js v20.12
Version: 23.0.115

## Description

I've generated some JSON Schema's, some of which must use regular expressions to enforce string formats.  But, the generated Zod code does not include the regex patterns.

## Input Data

This file is saved as `regex.yaml`

```yaml
$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://example.com/project.schema.json"
title: "Project"
description: "A product in the catalog"
type: "object"
properties:

    duration1:
        description: |
            A string conforming with ISO8601 duration strings, enforced
            by a regular expression pattern.
        type: string
        format: regex
        pattern: '^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$'

    duration2:
        description: |
            A string conforming with ISO8601 duration strings, enforced
            by a regular expression pattern.  This time without the regex format.
        type: string
        pattern: '^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$'

    year:
        description: |
            String of four digits meant to represent a year
        type: string
        pattern: '^[0-9][0-9][0-9][0-9]$'
```

## Expected Behaviour / Output

The generated Zod code should include:

```js
z.string().regex(regex);
```

This is documented at: https://zod.dev/?id=strings

## Current Behaviour / Output

The generated code is:

```js
import * as z from "zod";

export const RegexSchema = z.object({
    "duration1": z.string().optional(),
    "duration2": z.string().optional(),
    "year": z.string().optional(),
});
export type Regex = z.infer<typeof RegexSchema>;
```

Notice that the `regex` calls are missing.

## Steps to Reproduce

Using the above YAML, run:

```shell
npx quicktype -s schema ./regex.yaml --lang typescript-zod --out regex.ts
```
